{% set python_min = '3.10' %}
{% set name = "gufe" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }},<3.14
    - setuptools
    - versioningit
  run:
    - msgpack-python
    - networkx
    - numpy 
    - openff-toolkit-base >=0.15.1
    - openff-units >=0.3.1
    - openmm <8.3.1  # unpin once 8.3.1 is checked
    - pint
    - pip
    - pydantic >=2.0,<2.12
    - python >={{ python_min }}
    - rdkit !=2024.03.06
    - typing-extensions
    - zstandard

test:
  imports:
    - gufe
  requires:
    - pip
    - pooch
    - pytest
    - python {{ python_min }},<3.14 
  commands:
    - python -Ic "import gufe; print(gufe.__version__)"
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: "gufe"
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://gufe.openfree.energy
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - atravitz
