{% set name = "gufe" %}
{% set version = "1.0.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - versioningit
  run:
    - coverage
    - networkx
    - numpy 
    - openff-models
    - openff-toolkit >=0.13,<0.16
    - openff-units ==0.2.0
    - pint <0.22
    - pip
    - pydantic
    - python >=3.9
    - rdkit
    - typing-extensions

test:
  imports:
    - gufe
  requires:
    - pip
    - pytest
  commands:
    - python -Ic "import gufe; print(gufe.__version__)"
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: 'gufe: Grand Unified Free Energy'
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/OpenFreeEnergy/gufe
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - richardjgowers
