{% set python_min = '3.10' %}
{% set name = "gufe" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - versioningit
  run:
    - ambertools >=22
    - msgpack-python
    - networkx
    - numpy 
    - openff-toolkit-base >=0.13
    - openff-units >=0.3
    - openmm <8.2.0
    - pint
    - pip
    - pydantic >=1.10.17
    - python >={{ python_min }}
    - rdkit !=2024.03.06
    - typing-extensions
    - zstandard
  run_constrained:
    - openfe >1.3.0

test:
  imports:
    - gufe
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    - python -Ic "import gufe; print(gufe.__version__)"
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: 'gufe: Grand Unified Free Energy'
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://gufe.readthedocs.io/
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - atravitz
