{% set name = "gufe" %}
{% set version = "0.7.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: "2920551c1904bf6560bf0572b7778923c1de142f"

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - networkx
    - numpy <1.24.0
    - openff-models >=0.0.4
    - openff-toolkit
    - openff-units >=0.2.0
    - pip
    - python >=3.9
    - rdkit
    - typing-extensions

test:
  imports:
    - gufe
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: 'gufe: Grand Unified Free Energy'
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/OpenFreeEnergy/gufe
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - mikemhenry
    - richardjgowers
    - IAlibay
    - dwhswenson
    - dotsdl
