{% set name = "gufe" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/OpenFreeEnergy/{{ name }}.git
  git_rev: v{{ version }}
  git_depth: -1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
    - versioningit
  run:
    - networkx
    - numpy 
    - openff-models ~=0.1.2
    - openff-toolkit >=0.13
    - openff-units !=0.2.3,>=0.2,<0.3
    - openmm <8.2.0
    - pint
    - pip
    - pydantic >=1.10.17
    - python >=3.10
    - rdkit!=2024.03.06
    - typing-extensions

test:
  imports:
    - gufe
  requires:
    - pip
    - pytest
  commands:
    - python -Ic "import gufe; print(gufe.__version__)"
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: 'gufe: Grand Unified Free Energy'
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://gufe.readthedocs.io/
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - atravitz
