schema_version: 1

context:
  python_min: "3.11"
  name: gufe
  version: "1.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OpenFreeEnergy/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 7a8781df64c9248960eb6b46f9256972969bf1bc78688d526bf8457a20d5723c

build:
  number: 0
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*,<3.14
    - setuptools >=61.0
    - setuptools_scm
  run:
    - msgpack-python
    - networkx
    - numpy
    - openff-toolkit-base >=0.15.1
    - openff-units >=0.3.1
    - openmm
    - pint
    - pip
    - pooch >=1.9.0  # min needed for https://github.com/fatiando/pooch/issues/502
    - pydantic >=2.0,<2.12  # https://github.com/openforcefield/openff-interchange/issues/1346
    - python >=${{ python_min }}
    - rdkit >=2024.09.1  # github.com/OpenFreeEnergy/gufe/issues/664
    - typing-extensions
    - zstandard

tests:
  - python:
      imports:
        - gufe
      pip_check: false
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - pooch
        - pytest
        - python ${{ python_min }}.*
    script:
      - python -c "import ${{ name }}; print(${{ name }}.__version__)"
      - python -c "import ${{ name }}; assert(${{ name }}.__version__ == '${{ version }}')"
      - pytest -v --pyargs gufe

about:
  summary: gufe
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/OpenFreeEnergy/gufe
  repository: https://github.com/OpenFreeEnergy/gufe
  documentation: https://gufe.openfree.energy

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - atravitz
